[package]
name = "funandgames"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
time = "*"
byteorder = "*"

[dependencies.tap]
git = "https://github.com/acmcarther/rust_tap"

[dependencies.game_udp]
git = "https://github.com/acmcarther/rust_game_udp"

